# Pandas
- Open Source library in python we use for data manipulation and analysis
- two important data structures - Structural data - Series and DataFrame

### Why Pandas
- Easy handling structured data / Tabular data
- Itegrates well with

In [75]:
# pip install pandas

# Pandas Data Structures
- Series - One dimensional labelled array
- DataFrame - two dimensional table similar to a spreadsheet

In [76]:
import pandas as pd
import numpy as np

### Series: Key features
- labelled -  index
- can store different data types

### Creating Series

In [77]:
data = [3, 3.5, "anita"]
series = pd.Series(data)
print(series)

0        3
1      3.5
2    anita
dtype: object

In [78]:
pd.Series(data = [3, 7.7, "anita", 3, 7], index=['a', 'b', 'c', 'd', 'e'])

a        3
b      7.7
c    anita
d        3
e        7
dtype: object

In [79]:
# Write 10 names of students with custom index
pd.Series(data = ["Anita", "Krishna", "Pradip", "Sunita", "Anup", "Suman", "Desmond", "Erum", "Siddhartha", "Kuber"],
          index = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])

a         Anita
b       Krishna
c        Pradip
d        Sunita
e          Anup
f         Suman
g       Desmond
h          Erum
i    Siddhartha
j         Kuber
dtype: object

### DataFrames: Key Features
- Multiple columns
- can handle missing values
- supports indexing
### Creating dictionary from Series

In [80]:
data = {
    "Name": ['Alice', 'Anita', 'Bob'],
    'Age': [25, 30, 34]
}
df = pd.DataFrame(data)
print(df)

    Name  Age
0  Alice   25
1  Anita   30
2    Bob   34

## Data input and output
### Reading data with pandas

In [81]:
# Read csv file
csv_data = pd.read_csv(r"C:\Users\Anita\Desktop\DataScience-and-ML\Phase_1\Section_2\Day_002\movies.csv")
print(csv_data)

                                   MOVIES         YEAR  \
0                           Blood Red Sky       (2021)
1     Masters of the Universe: Revelation     (2021– )
2                        The Walking Dead  (2010–2022)
3                          Rick and Morty     (2013– )
4                         Army of Thieves       (2021)
...                                   ...          ...
9994                       The Imperfects     (2021– )
9995                               Arcane     (2021– )
9996                    Heart of Invictus     (2022– )
9997                       The Imperfects     (2021– )
9998                       The Imperfects     (2021– )

                                           GENRE  RATING  \
0         \nAction, Horror, Thriller                 6.1
1     \nAnimation, Action, Adventure                 5.0
2          \nDrama, Horror, Thriller                 8.2
3     \nAnimation, Adventure, Comedy                 9.2
4            \nAction, Crime, Horror                 NaN
...                                          ...     ...
9994     \nAdventure, Drama, Fantasy                 NaN
9995  \nAnimation, Action, Adventure                 NaN
9996            \nDocumentary, Sport                 NaN
9997     \nAdventure, Drama, Fantasy                 NaN
9998     \nAdventure, Drama, Fantasy                 NaN

                                               ONE-LINE  \
0     \nA woman with a mysterious illness is forced ...
1     \nThe war for Eternia begins again in what may...
2     \nSheriff Deputy Rick Grimes wakes up from a c...
3     \nAn animated series that follows the exploits...
4     \nA prequel, set before the events of Army of ...
...                                                 ...
9994                                     \nAdd a Plot\n
9995                                     \nAdd a Plot\n
9996                                     \nAdd a Plot\n
9997                                     \nAdd a Plot\n
9998                                     \nAdd a Plot\n

                                                  STARS    VOTES  RunTime  \
0     \n    Director:\nPeter Thorwarth\n| \n    Star...   21,062    121.0
1     \n            \n    Stars:\nChris Wood, \nSara...   17,870     25.0
2     \n            \n    Stars:\nAndrew Lincoln, \n...  885,805     44.0
3     \n            \n    Stars:\nJustin Roiland, \n...  414,849     23.0
4     \n    Director:\nMatthias Schweighöfer\n| \n  ...      NaN      NaN
...                                                 ...      ...      ...
9994  \n            \n    Stars:\nMorgan Taylor Camp...      NaN      NaN
9995                                                 \n      NaN      NaN
9996  \n    Director:\nOrlando von Einsiedel\n| \n  ...      NaN      NaN
9997  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      NaN
9998  \n    Director:\nJovanka Vuckovic\n| \n    Sta...      NaN      NaN

     Gross
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
...    ...
9994   NaN
9995   NaN
9996   NaN
9997   NaN
9998   NaN

[9999 rows x 9 columns]

In [82]:
#  Reading excel data
excel_data = pd.read_excel(r"C:\Users\Anita\Desktop\DataScience-and-ML\Phase_1\Section_2\Day_002\electricity_consumption.xlsx")
print(excel_data)

              timestamp region  consumption
0   2020-01-01 00:00:00  North   420.051464
1   2020-01-01 01:00:00   West   946.388751
2   2020-01-01 02:00:00  South   788.792728
3   2020-01-01 03:00:00  North   773.797258
4   2020-01-01 04:00:00   West   913.347766
..                  ...    ...          ...
495 2020-01-21 15:00:00   East   173.232639
496 2020-01-21 16:00:00   West   893.706853
497 2020-01-21 17:00:00   East   747.658142
498 2020-01-21 18:00:00  South   969.750974
499 2020-01-21 19:00:00   East   556.871993

[500 rows x 3 columns]

In [83]:
# Writing files (Output)
print(df)

    Name  Age
0  Alice   25
1  Anita   30
2    Bob   34

In [84]:
# Writing data to a csv file
df.to_csv("example_data.csv", index=False)

In [85]:
# Writing data to an excel file
df.to_excel("details.xlsx", index=False) # create excel file without index

## Data Seletion and Indexing

### Selecting columns in dataframe(df)

In [86]:
print(df)

    Name  Age
0  Alice   25
1  Anita   30
2    Bob   34

In [87]:
# Select the column called "Name"
print(df["Name"])

0    Alice
1    Anita
2      Bob
Name: Name, dtype: object

In [88]:
df["Name"]

0    Alice
1    Anita
2      Bob
Name: Name, dtype: object

In [89]:
data = {
    "Name": ['Alice', 'Anita', 'Bob'],
    'Age': [25, 30, 34],
    'City': ["New York", "Kathmandu", "Butwal"]
}
df = pd.DataFrame(data)

In [90]:
df

    Name  Age       City
0  Alice   25   New York
1  Anita   30  Kathmandu
2    Bob   34     Butwal

In [91]:
# Selecting multiple columns in df
df[["Name", "City"]] # Double square bracket

    Name       City
0  Alice   New York
1  Anita  Kathmandu
2    Bob     Butwal

In [92]:
# Selecting rows
df

    Name  Age       City
0  Alice   25   New York
1  Anita   30  Kathmandu
2    Bob   34     Butwal

In [93]:
# selecting row by label
df.loc[1]

Name        Anita
Age            30
City    Kathmandu
Name: 1, dtype: object

In [94]:
# selecting row by index
df.iloc[2]

Name       Bob
Age         34
City    Butwal
Name: 2, dtype: object

# Filtering the data using pandas

In [95]:
df

    Name  Age       City
0  Alice   25   New York
1  Anita   30  Kathmandu
2    Bob   34     Butwal

In [96]:
df_filter = df[df["Age"] >= 30 ] 
df_filter

    Name  Age       City
1  Anita   30  Kathmandu
2    Bob   34     Butwal

# Cleaning and Manipulating data

## Rename columns

In [97]:
df.rename(columns = {"Name":  "First Name"}, inplace = True)

In [98]:
df

  First Name  Age       City
0      Alice   25   New York
1      Anita   30  Kathmandu
2        Bob   34     Butwal

In [99]:
# Dropping columns
df.drop(columns = ["Age"], inplace = True)

In [100]:
df

  First Name       City
0      Alice   New York
1      Anita  Kathmandu
2        Bob     Butwal

In [104]:
# Replace values in the particular column
df["City"] = df["City"].replace("Butwal", "Santa Clara")

In [105]:
df

  First Name         City
0      Alice     New York
1      Anita    Kathmandu
2        Bob  Santa Clara

In [ ]:
# Sorting Data
df.sort_values('City', ascending=False, inplace=True) # Sorting in descending order
df

  First Name         City
2        Bob  Santa Clara
0      Alice     New York
1      Anita    Kathmandu

In [ ]:
#